version: "3"

services:
  node01:
    image: "floatilla:0.01"
    restart: unless-stopped
#    depends_on:
#      - mariadb
#    ports:
#      - '8091:8090'


  node02:
    image: "floatilla:0.01"
    restart: unless-stopped
       depends_on:
         - node01
#    ports:
#      - '8092:8090'

  node03:
    image: "floatilla:0.01"
    restart: unless-stopped
       depends_on:
         - node02
#    ports:
#      - '8093:8090'


  node04:
    image: "floatilla:0.01"
    restart: unless-stopped
       depends_on:
         - node03
#    ports:
#      - '8094:8090'
